### PR TITLE
Optionally return the dislocation core fit error.

### PR DESCRIPTION
**Pull request by imaliyov**
Modified the `fit_core_position()` and `fit_core_position_images()` functions of the `dislocation.py` module.
`return_error` and `return_errors` flags added. If `True`, the functions will return the error of the `scipy.optimize.minimize` fit of the dislocation core position. This will require an additional `cost_function()` call. This probably can be avoided in the future if the error can be obtained directly from the `minimize()` function.

### CODE REVIEW

**Comment by jameskermode** [comment]
@pgrigorev or @thomas-rocke would one of you be willing to take a look at this PR?

**Comment by pgrigorev** [comment]
@jameskermode, we have already discussed this PR with Ivan, but I will have a closer look on the changes and let you know here.

**Comment by jameskermode** [comment]
The failing tests are due to an ASE change, which could be fixed here or in a separate PR. I think `ase.neb` has moved to `ase.mep.neb`.

**Comment by pgrigorev** [comment]
ah I see. Yes we should fix that. I guess the best way would be to check ase version on import to keep backward compatibility?

**Comment by pgrigorev** [comment]
I think the tests failing tests have been fixed now, @imaliyov could you merge it to your branch?

**Comment by imaliyov** [comment]
@pgrigorev thank you, I have merged it to my branch.

**Review by pgrigorev — APPROVED** [review]
Everything looks good, I am sure it is safe to merge!

**Comment by pgrigorev** [comment]
Sorry it took so long, but after having  a look on the changes I think it is safe to merge. (the changes are really minor)

**Comment by jameskermode** [comment]
Thanks!

**Pull request merged**
