### PR TITLE
Dislocation

### PR DESCRIPTION
**Pull request by pgrigorev**
Hi,
Here are some developments of the dislocation.py module, some minor changes and fixed typos.
Best Regards,
Petr

### CODE REVIEW

**Comment by pastewka** [comment]
Hi @pgrigorev are there tests for `read_dislo_QMMM` and `make_barrier_configurations`?

@jameskermode How strict do we want to be with tests? (I'm happy to be reasonably lenient.)

**Comment by pgrigorev** [comment]
@pastewka there are no tests at the moment. But I agree that tests should be added.

**Comment by pastewka** [comment]
Happy to merge as is. Tests can be added later.

**Comment by pgrigorev** [comment]
Thank you!

**Pull request merged**
