### PR TITLE
New dislocation generator

### PR DESCRIPTION
**Pull request by jameskermode**

### CODE REVIEW

**Comment by jameskermode** [comment]
@pgrigorev can you take a look at this and let me know what you think?

**Review by pgrigorev — COMMENTED** [review]
It all looks good to me. However do you think it would make sense to keep the atoms objects of disloc and bulk as a part of the class attributes? Maybe the Stroh object as well. It can be initialised as None and then assigned values when the buld_cylinder is called. My idea is to keep the data as a part of the object because it can be later used by analysis functions like cost functions, fitting the core position etc. (if we want to make these functions as class methods)

**Comment by jameskermode** [comment]
Thanks, good idea for the Stroh object certainly. The Atoms depend on the radius passed to `build_cylinder()` so I think they should not be stored.

**Comment by jameskermode** [comment]
Did you try the ovito DXA tests? Should work after a `pip install ovito`, but won't work in the CI yet. I'll try to update the Travis config to install Ovito.

**Comment by pgrigorev** [comment]
I have not tried the Ovito test so far. But I will and let you know how it goes.

**Review by pgrigorev — COMMENTED** [review]
Do I understand correctly that you expect ising dislocation objects to create multiple atomistic configurations? I was thinking to keep everthing including atoms object as well as the corresponding radius in the object. That would imply using one dislocation object for one atomistic configuration. The motivation for that is atomistic configuration on its own is not very useful. Ideally you need to know the axes, displacement, radius, core position etc. it would make sense to me to store it all together. But I might be wrong.

**Comment by jameskermode** [comment]
Yes that is what I meant. I agree most of the time you need everything, but I wanted to separate the abstract description of the dislocation from a particular atomistic cylinder. For example, you could create one dislocation object and use it to build cylinders with larger and larger radii to test convergence.

**Comment by pgrigorev** [comment]
ok, I see what you mean. That makes sense and it is probably better to keep things more general.

**Comment by pgrigorev** [comment]
> Did you try the ovito DXA tests? Should work after a `pip install ovito`, but won't work in the CI yet. I'll try to update the Travis config to install Ovito.

After I commented out the `test_differential_displacement` test due to the reasons mentioned in the comment above, I was able to run test involving calling `Ovito` functions. So I think it works pretty well.

**Comment by jameskermode** [comment]
> I think we have to find a way to work with the version that comes from doing `pip install atomman`. I’ll try to fix the failing test and see if I can come up with a workaround.

Hmm, I can't find a workaround. I was hoping I could copy from the atomman-generated figure into `plot_axes`, but I can't get this to work since Artists can't be reused from one plot to another.  I'll revert the change to `plot_vitek()` in this PR and we can return to this later.

**Comment by pgrigorev** [comment]
> > I think we have to find a way to work with the version that comes from doing `pip install atomman`. I’ll try to fix the failing test and see if I can come up with a workaround.
> 
> Hmm, I can't find a workaround. I was hoping I could copy from the atomman-generated figure into `plot_axes`, but I can't get this to work since Artists can't be reused from one plot to another. I'll revert the change to `plot_vitek()` in this PR and we can return to this later.

Yes, this was my whole point to add and also why I was trying to push to be included in the main `atomman` distribution.  I was hoping to have a version of 'atomman' in the official repo, but I think they did something messed up with git at some point and end up erasing my commit. So we have to stick to my fork if we want this functionality. However this test is executed only if matplotlib is installed. So at least it can be used for calculations without visualisations.

**Pull request merged**
