### PR TITLE
MAINT: Remodel electrochemistry module interface API to adhere to PEP-8 conventions

### LINKED ISSUE #216: Part of the electrochemistry module does not follow coding style
We adhere to PEP-8, which mentions "Function names should be lowercase, with words separated by underscores as necessary to improve readability." Part of the electrochemisty module uses CamelCase.

Example:
https://github.com/libAtoms/matscipy/blob/ba2179106680a102d4510d2be1bdf8374c3be645/matscipy/electrochemistry/poisson_nernst_planck_solver.py#L382

### PR DESCRIPTION
**Pull request by jotelha**
Closes #216

### CODE REVIEW

**Comment by jotelha** [comment]
Also enables running tests on pull requests and provides fenics in test workflow.

**Comment by jotelha** [comment]
The only tests left failing now are the
```
 FAILED test_dislocation.py::TestDislocation::test_edge100110_dislocation_adsl - TypeError: unsupported operand type(s) for -: 'Atom' and 'float'
FAILED test_dislocation.py::TestDislocation::test_edge100_dislocation_adsl - TypeError: unsupported operand type(s) for -: 'Atom' and 'float'
FAILED test_dislocation.py::TestDislocation::test_edge111bar_dislocation_adsl - TypeError: unsupported operand type(s) for -: 'Atom' and 'float'
FAILED test_dislocation.py::TestDislocation::test_edge_dislocation_adsl - TypeError: unsupported operand type(s) for -: 'Atom' and 'float'
FAILED test_dislocation.py::TestDislocation::test_mixed_dislocation_adsl - TypeError: unsupported operand type(s) for -: 'Atom' and 'float'
FAILED test_dislocation.py::TestDislocation::test_screw_dislocation_adsl - TypeError: unsupported operand type(s) for -: 'Atom' and 'float'
```
dislocation tests unrelated to the electrochemistry module.

**Review by pastewka — APPROVED** [review]

**Comment by jameskermode** [comment]
I think those dislocation tests will be fixed once #206 is merged

**Comment by pastewka** [comment]
Okay. Should we disable those tests for now or is the fix simple? If simple we could just fold it into the code.

**Comment by jameskermode** [comment]
@thomas-rocke can you comment on this? I recall you said you'd fixed these failures somewhere

**Comment by thomas-rocke** [comment]
I've got a fix sat on #206, the tests were broken in the ADSL PR (#201), but were skipped due to the atomman dependancy (atomman was later added to the CI, which is why they're now being caught). I can try to make a separate hotfix PR if we want to solve this ASAP, but it will be fixed anyway when #206 is merged. 

There's nothing actually wrong with the ADSL code, the fix is only for the unittests, so it shouldn't be an issue for most end users regardless of when it gets fixed. Finishing #206 is one of my main priorities now, so I hope to get it done soon (likely in a week or two).

**Comment by pastewka** [comment]
Okay, I will xfail the tests for now.

**Pull request merged**
