### PR TITLE
Improvements to Sphinx documentation's structure and look

### PR DESCRIPTION
**Pull request by arn-all**
Hi,

This PR is just a modest proposition of improvement to the sphinx documentation's look and feel.

- I converted the existing `README.md` to `README.rst`, which is natively supported by Sphinx and github (.md is not supported by Sphinx), and put it in the docs' front page as it's common practice.
- I changed the default theme to the very popular `rtd_theme`. It introduces a new dependency though. You might prefer [another theme](https://sphinx-themes.org/), it's just an example.
- I added a modules table to the same page, created using the [autosummary extension](http://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#module-sphinx.ext.autosummary). It allows to insert a short description of each module, taken from docstrings. If you like this feature, the table should be filled-in by adding more docstrings to the code. Only a few entries were found for now.

As I said, it's just options: feel free to take or leave any of them !

### CODE REVIEW

**Comment by pastewka** [comment]
Looks good

**Comment by pastewka** [comment]
And thanks!

**Comment by arn-all** [comment]
The [online  documentation](http://libatoms.github.io/matscipy/) didn't get the update, as the branch `gh-pages` (which is the publishing source of the repo by default) wasn't modified. 

I'd suggest to [change the publishing source](https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source) to `master/docs`, which would make it easier to generate the docs directly from the code of `master`. 
To do this, instead of manually commit the build results, I guess it'd be much more convenient to let some CI ([a GH Action maybe ?](https://github.com/ammaraskar/sphinx-action)) generate the [html automatically](https://www.docslikecode.com/articles/github-pages-python-sphinx/).

**Comment by pastewka** [comment]
Sounds good. Do you want to take care of this?

**Comment by arn-all** [comment]
I'll give it a try on a forked repo and let you know !

**Comment by arn-all** [comment]
I managed to have the docs [online](https://arn-all.github.io/matscipy/index.html), but still have an issue with some of the modules of matscipy that import `_matscipy`. 
When ran on GH, Sphinx isn't able to import them, whilst it works on my computer : 

```
WARNING: autodoc: failed to import module 'angle_distribution' from module 'matscipy'; the following exception was raised:
No module named '_matscipy'
```

In the opposite, files with `import matscipy` work fine. What does this leading underscore stand for ?

**Comment by pastewka** [comment]
The leading underscore is the C-extension module. All C-functions are typically wrapped again within Python. If the documentation system does not build the C-extension, it will not be available.

A way around this maybe to skip importing this when building the docs, since there is little documentation in the C-extensions.


________________________________
Von: arn-all <notifications@github.com>
Gesendet: Mittwoch, 6. Mai 2020 12:03
An: libAtoms/matscipy
Cc: Lars Pastewka; State change
Betreff: Re: [libAtoms/matscipy] Improvements to Sphinx documentation's structure and look (#28)

**Pull request merged**
