### PR TITLE
MAINT: Move scripts to (installable) CLI

### PR DESCRIPTION
**Pull request by pastewka**
We currently have a folder called "scripts" that contains what really are command line helper tools. It would be good to formally have those as command line tools and install them via pip.

Every command will be prefixed with `matscipy_` to avoid naming collisions.

### CODE REVIEW

**Comment by jameskermode** [comment]
I'll add the more well-used fracture scripts to this PR before we merge it.

**Comment by pastewka** [comment]
Okay thanks. Do you agree that we prefix everything with `matscipy_`? Could also use `matscipy-`. We could think about a script naming convention, e.g. everything hyphenized: `matscipy-average-eam-potential` or everything underscores `matscipy_average_eam_potential` or mixed `matscipy_average-eam-potential`. Any opinions @jameskermode @jotelha ?

**Comment by jameskermode** [comment]
I would prefer everything hythenized for command line tools, slightly faster to type.  We should be consistent, so we should replace any existing `_` with `-` in the script names.

**Comment by pastewka** [comment]
Okay, agreed!

**Comment by pastewka** [comment]
An everything small case, no capital letters?

**Comment by jameskermode** [comment]
Yes

**Comment by jotelha** [comment]
Agreed, all hyphenized small case, e.g `matscipy-poisson-nernst-planck`.

**Review by jameskermode — APPROVED** [review]

**Pull request merged**
