### PR TITLE
Added electrochemistry sub-module with Poisson-Nernst-Planck solver a…

### PR DESCRIPTION
**Pull request by jotelha**
Strictly speaking, no chemistry involved here so far, just simple 1D EDL (electrical double layer) without any reacting species.

 `requirements.txt` is back to master version, with additional "wheel" and "atomman", otherwise tests/test_dislocation.py tests fail locally.

```
wheel
numpy>=1.5.0
ase>=3.9.0
atomman
#scipy>=0.10.0
sphinxcontrib-napoleon
```

ASE had several issues in the LAMMPS data file export that were only fixed recently:

- https://gitlab.com/ase/ase/commit/4a1cc4d85a0b9c82349ed5ef1fa8f9fc9a939d41
- https://gitlab.com/ase/ase/commit/4e56a24d1250895eb51295acf93459b2ef515a5b

Thus, LAMMPS data file export with  'c2d.py' requires recent development version of ASE.  test_c2d.py:test_c2d_input_format_npz_output_format_lammps is skipped unless ASE version > 3.18.1.

While the freshly added tests run without issues, I was not able to get all the previous tests to run locally. Even when installing in a fresh venv (Python 3.6.8) with a minimal set of dependencies installed according to the requirement file with `pip install -r requirements.txt`,

```
ase==3.18.1
atomman==1.3.1
cycler==0.10.0
Cython==0.29.14
DataModelDict==0.9.6
kiwisolver==1.1.0
matplotlib==3.1.2
-e git+git@github.com:libAtoms/matscipy.git@5449950e02343112bb20d5ee17fbef2cf82a89f6#egg=matscipy
numericalunits==1.24
numpy==1.17.4
pandas==0.25.3
pkg-resources==0.0.0
pockets==0.9.1
pyparsing==2.4.5
python-dateutil==2.8.1
pytz==2019.3
scipy==1.3.3
six==1.13.0
sphinxcontrib-napoleon==0.7
toolz==0.10.0
xmltodict==0.12.0
```

the following tests fail locally:
* test_rotation (rotation_of_elastic_constants.TestCubicElasticModuli)
* test_core_position (test_dislocation.TestDislocation)
* test_forces_CuZr_glass (eam_calculator.TestEAMCalculator)
* test_CuZr (eam_calculator.TestEAMCalculator)
* test_direct_evaluation (eam_calculator.TestEAMCalculator)
* test_stress (eam_calculator.TestEAMCalculator)

The command `python run_tests.py` called from within `tests` subfolder (in a fashion equivalent to what I see happening on this Travis CI platform) yields the following output:

```
........./home/jotelha/venv/jlh-testing-python-3.6.8-20191212/lib/python3.6/site-packages/scipy/integrate/quadrature.py:251: AccuracyWarning: maxiter (200) exceeded. Latest difference = 5.691650e-05
  AccuracyWarning)
/home/jotelha/venv/jlh-testing-python-3.6.8-20191212/lib/python3.6/site-packages/scipy/integrate/quadrature.py:251: AccuracyWarning: maxiter (50) exceeded. Latest difference = 5.451408e-07
  AccuracyWarning)
/home/jotelha/venv/jlh-testing-python-3.6.8-20191212/lib/python3.6/site-packages/scipy/integrate/quadrature.py:251: AccuracyWarning: maxiter (50) exceeded. Latest difference = 4.829120e-07
  AccuracyWarning)
/home/jotelha/venv/jlh-testing-python-3.6.8-20191212/lib/python3.6/site-packages/scipy/integrate/quadrature.py:251: AccuracyWarning: maxiter (50) exceeded. Latest difference = 2.861273e-07
  AccuracyWarning)
/home/jotelha/venv/jlh-testing-python-3.6.8-20191212/lib/python3.6/site-packages/scipy/integrate/quadrature.py:251: AccuracyWarning: maxiter (200) exceeded. Latest difference = 9.477370e-04
  AccuracyWarning)
/home/jotelha/venv/jlh-testing-python-3.6.8-20191212/lib/python3.6/site-packages/scipy/integrate/quadrature.py:251: AccuracyWarning: maxiter (200) exceeded. Latest difference = 1.416756e-05
  AccuracyWarning)
/home/jotelha/venv/jlh-testing-python-3.6.8-20191212/lib/python3.6/site-packages/scipy/integrate/quadrature.py:251: AccuracyWarning: maxiter (200) exceeded. Latest difference = 9.065385e-06
  AccuracyWarning)
....../mnt/jlh/home/jotelha/git/matscipy/matscipy/calculators/eam/calculator.py:94: ResourceWarning: unclosed file <_io.TextIOWrapper name='Au-Grochola-JCP05.eam.alloy' mode='r' encoding='UTF-8'>
  source, parameters, F, f, rep = read_eam(fn, kind=kind)
/mnt/jlh/home/jotelha/git/matscipy/matscipy/elasticity.py:341: UserWarning: CubicElasticModuli is deprecated. Use rotate_elastic_constants function instead.
  warnings.warn('CubicElasticModuli is deprecated. Use '
EEF./mnt/jlh/home/jotelha/git/matscipy/matscipy/calculators/eam/calculator.py:94: ResourceWarning: unclosed file <_io.TextIOWrapper name='CuAg.eam.alloy' mode='r' encoding='UTF-8'>
  source, parameters, F, f, rep = read_eam(fn, kind=kind)
F.EF..../mnt/jlh/home/jotelha/git/matscipy/tests/greens_function.py:48: RuntimeWarning: invalid value encountered in sqrt
  P = np.where(r_sq > 1., np.zeros_like(r_sq), np.sqrt(1.-r_sq))
./mnt/jlh/home/jotelha/git/matscipy/tests/greens_function.py:79: RuntimeWarning: invalid value encountered in sqrt
  P = np.where(r_sq > 1., np.zeros_like(r_sq), np.sqrt(1.-r_sq))
./mnt/jlh/home/jotelha/git/matscipy/tests/greens_function.py:115: RuntimeWarning: invalid value encountered in sqrt
  P = np.where(r_sq > 1., np.zeros_like(r_sq), np.sqrt(1.-r_sq))
../mnt/jlh/home/jotelha/git/matscipy/matscipy/contact_mechanics/Hertz.py:140: RuntimeWarning: divide by zero encountered in true_divide
  srr = -(1.+poisson)*(1.-z*np.arctan(1./z)) + 1./(2.*(1.+z**2))
/mnt/jlh/home/jotelha/git/matscipy/matscipy/contact_mechanics/Hertz.py:234: RuntimeWarning: divide by zero encountered in true_divide
  sqrtu_arctan_inv_sqrtu = sqrtu*np.arctan(1./sqrtu)
../mnt/jlh/home/jotelha/git/matscipy/matscipy/contact_mechanics/Hertz.py:246: RuntimeWarning: invalid value encountered in true_divide
  z2_div_u_plus_z2 = np.where(u_plus_z2 > 0., z**2/u_plus_z2, np.ones_like(z))
........../mnt/jlh/home/jotelha/git/matscipy/tests/spatial_correlation_function.py:114: RuntimeWarning: invalid value encountered in true_divide
  n_peaks0=np.isfinite(SCF0/SCF0).sum()
/mnt/jlh/home/jotelha/git/matscipy/tests/spatial_correlation_function.py:115: RuntimeWarning: invalid value encountered in true_divide
  n_peaks1=np.isfinite(SCF1/SCF1).sum()
/mnt/jlh/home/jotelha/git/matscipy/tests/spatial_correlation_function.py:116: RuntimeWarning: invalid value encountered in true_divide
  n_peaks2=np.isfinite(SCF2/SCF2).sum()
..s../usr/lib/python3.6/unittest/case.py:605: ResourceWarning: unclosed file <_io.TextIOWrapper name=6 encoding='utf-8'>
  testMethod()
...
======================================================================
ERROR: test_rotation (rotation_of_elastic_constants.TestCubicElasticModuli)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/jlh/home/jotelha/git/matscipy/tests/rotation_of_elastic_constants.py", line 91, in test_rotation
    a = make_atoms(latticeconstant, directions)
  File "/mnt/jlh/home/jotelha/git/matscipy/tests/rotation_of_elastic_constants.py", line 57, in <lambda>
    latticeconstant=a0, directions=x),
  File "/home/jotelha/venv/jlh-testing-python-3.6.8-20191212/lib/python3.6/site-packages/ase/lattice/bravais.py", line 58, in __call__
    self.find_directions(directions, miller)
  File "/home/jotelha/venv/jlh-testing-python-3.6.8-20191212/lib/python3.6/site-packages/ase/lattice/cubic.py", line 71, in find_directions
    Bravais.find_directions(self, directions, miller)
  File "/home/jotelha/venv/jlh-testing-python-3.6.8-20191212/lib/python3.6/site-packages/ase/lattice/bravais.py", line 375, in find_directions
    directions[k]))
  File "/home/jotelha/venv/jlh-testing-python-3.6.8-20191212/lib/python3.6/site-packages/ase/lattice/bravais.py", line 445, in reduceindex
    g = gcd(M[0], M[1])
TypeError: 'numpy.float64' object cannot be interpreted as an integer

======================================================================
ERROR: test_core_position (test_dislocation.TestDislocation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/jlh/home/jotelha/git/matscipy/tests/test_dislocation.py", line 42, in test_core_position
    method='Nelder-Mead')
  File "/home/jotelha/venv/jlh-testing-python-3.6.8-20191212/lib/python3.6/site-packages/scipy/optimize/_minimize.py", line 588, in minimize
    return _minimize_neldermead(fun, x0, args, callback, **options)
  File "/home/jotelha/venv/jlh-testing-python-3.6.8-20191212/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 586, in _minimize_neldermead
    fsim[k] = func(sim[k])
  File "/home/jotelha/venv/jlh-testing-python-3.6.8-20191212/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 327, in function_wrapper
    return function(*(wrapper_args + args))
  File "/mnt/jlh/home/jotelha/git/matscipy/matscipy/dislocation.py", line 696, in cost_function
    print_info=print_info)
  File "/mnt/jlh/home/jotelha/git/matscipy/matscipy/dislocation.py", line 627, in compare_configurations
    u_extended[mapping.values(), :] = u
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: test_forces_CuZr_glass (eam_calculator.TestEAMCalculator)
Calculate interatomic forces in CuZr glass
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/jlh/home/jotelha/git/matscipy/tests/eam_calculator.py", line 210, in test_forces_CuZr_glass
    atoms = io.read("CuZr_glass_460_atoms_forces.lammps.dump.gz", format="lammps-dump")
  File "/home/jotelha/venv/jlh-testing-python-3.6.8-20191212/lib/python3.6/site-packages/ase/io/formats.py", line 498, in read
    parallel=parallel, **kwargs))
  File "/home/jotelha/venv/jlh-testing-python-3.6.8-20191212/lib/python3.6/site-packages/ase/io/formats.py", line 556, in _iread
    for dct in io.read(fd, *args, **kwargs):
  File "/home/jotelha/venv/jlh-testing-python-3.6.8-20191212/lib/python3.6/site-packages/ase/io/formats.py", line 354, in wrap_read_function
    for atoms in read(filename, index, **kwargs):
TypeError: read_lammps_dump() takes 1 positional argument but 2 were given

======================================================================
FAIL: test_CuZr (eam_calculator.TestEAMCalculator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/jlh/home/jotelha/git/matscipy/tests/eam_calculator.py", line 152, in test_CuZr
    self.assertAlmostEqual(a_Cu, 3.639, 3)
AssertionError: 3.6885976664722535 != 3.639 within 3 places

======================================================================
FAIL: test_direct_evaluation (eam_calculator.TestEAMCalculator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/jlh/home/jotelha/git/matscipy/tests/eam_calculator.py", line 133, in test_direct_evaluation
    (syms=='Ag').sum()*e_Ag)/len(a)-0.177)<0.0003)
AssertionError: False is not true

======================================================================
FAIL: test_stress (eam_calculator.TestEAMCalculator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/jlh/home/jotelha/git/matscipy/tests/eam_calculator.py", line 72, in test_stress
    self.assertArrayAlmostEqual(a.get_stress(), calc.calculate_numerical_stress(a), tol=self.tol)
  File "/mnt/jlh/home/jotelha/git/matscipy/tests/matscipytest.py", line 103, in assertArrayAlmostEqual
    (absdiff.max(), loc))
AssertionError: Maximum abs difference between array elements is 8.438534e-04 at location (5,)

----------------------------------------------------------------------
Ran 51 tests in 798.133s

FAILED (failures=3, errors=3, skipped=1)
skin_x = 0.5*a0, skin_y = 0.5*a0
skin_x = 0.7071067811865476, skin_y = 0.7071067811865476
skin_x = 0.5*a0, skin_y = 0.5*a0
skin_x = 0.7071067811865476, skin_y = 0.7071067811865476
skin_x = 0.5*a0, skin_y = 0.5*a0
skin_x = 0.7071067811865476, skin_y = 0.7071067811865476
skin_x = 0.5*a0, skin_y = 0.5*a0
skin_x = 0.7071067811865476, skin_y = 0.7071067811865476
Making a local comparison with radius 40.00
a
[-0.00289987  0.0244164   0.06739786 -0.00505605  0.0003557   0.05268925]

b
[-0.00284692  0.02425209  0.06741898 -0.00503533 -0.00011954  0.0518454 ]

Absolute difference
[5.29421497e-05 1.64313461e-04 2.11163570e-05 2.07164608e-05
 4.75237320e-04 8.43853379e-04]
  RUN test_c2d_input_format_npz_output_format_xyz
  RUN test_c2d_input_format_txt_output_format_xyz
  RUN test_pnp_c2d_pipeline_mode
  RUN test_pnp_output_format_npz
  RUN test_pnp_output_format_txt
```

While writing this comment, Travis CI tests failed again not beeing able to find the new `matscipy.electrochemistry' module. I might need some help here, no experience with these CI platforms.

### CODE REVIEW

**Comment by pastewka** [comment]
A ˋmatplotlibˋ import should be avoided within ˋmatscipyˋ modules. Plotting from examples or scripts is okay, plotting from within the library should not happen.

**Comment by jotelha** [comment]
Thanks! The Travis CI checks here will always fail as long as there is no scipy within the testing system.

**Comment by pastewka** [comment]
scipy should be optional. All tests should run.without it. Why do you need scipy?

**Comment by jotelha** [comment]
All fundamental physical constants within the electrochemistry part are imported from scipy.
More important, the rejection sampler uses scipy.optimize (https://github.com/libAtoms/matscipy/blob/933b7be23503f141013f912b4acbef8a817dbda2/matscipy/electrochemistry/continuous2discrete.py#L216-L217) and scipy.integrate (https://github.com/libAtoms/matscipy/blob/933b7be23503f141013f912b4acbef8a817dbda2/matscipy/electrochemistry/continuous2discrete.py#L318).

**Comment by pastewka** [comment]
I can't decide this by myself.

@jameskermode Do we want a dependency on scipy. This would mean tests won't run without it (but parts of the code will).

**Comment by jameskermode** [comment]
ASE now depends on scipy so I'm find with us requiring it too

**Comment by pastewka** [comment]
Wasn't aware of that, but sounds good. @jotelha can you adjus the CI files so that the tests run in CI?

**Comment by jotelha** [comment]
https://github.com/libAtoms/matscipy/pull/27

Would that do? Some of the tests depend on scipy and probably never ran in Travis CI, due to a clause in run_tests.py checking for scipy. These might need some attention, I would have no idea how to make them work. For now, just disabled them.

**Pull request merged**
