### PR TITLE
DOC: JOSS submission and updated documentation

### LINKED ISSUE #108: Publication of a paper about matscipy
So far, while citing `matscipy` in our papers I had to use a web citation to the repository that always feels a bit _ad-hoc_. Thus I was thinking that it would be nice to have a paper published to be able to formally cite the code. Moreover, it can help all of us to get more formal recognition of our efforts. This issue is essentially to discuss how we can achieve this. 

After a short discussion about it wit @jameskermode we decided that [Journal of Open Source Software](https://joss.theoj.org/) looks like a nice option. It requires only a very short (250-1000 words) high level description of the software, but the review is more focused on the software itself: installation, tests coverage and documentation.  You can find more details on [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) and [reviewer checklist](https://joss.readthedocs.io/en/latest/review_checklist.html) pages. 

We should host the `paper.md` file as a part of the repository, that can be in a short lived branch that is never merged to the main repository. Then everyone can add a small bit with the description of the parts of the code that they developed together with more general description. I am happy to volunteer to do the bookkeeping for this branch and the submission itself.

It seems to me that in the current shape `matscipy` already passes most of the requirements and writing a short summary should not take too long. However, before starting working on the submission it makes sense to understand if there are parts of `matscipy` that require a significant rework before the submission. I would suggest using the discussion on this issue to provide your opinions. On my site, I probably should enable building the documentation for the `dislocation.py` module as well as to think about solving a dependency on `atomman` package. 

I am happy to discuss other options and suggestions as well.

### PR DESCRIPTION
**Pull request by pastewka**
This PR contains the JOSS submission of matscipy. We also updated and expanded the formal documentation of the code.

Closes #108

### CODE REVIEW

**Comment by prs513rosewood** [comment]
For reference: when using Jupyter notebooks for the documentation, the correct format for the sphinx directives like `` :py:class:`matscipy.calculators.MatscipyCalculator` `` is `` {py:class}`matscipy.calculators.MatscipyCalculator` `` [as documented here](https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#reference-roles).

**Comment by prs513rosewood** [comment]
Since we're making documentation changes, I think it would be interesting to setup [doc builds on pull-requests](https://docs.readthedocs.io/en/stable/guides/pull-requests.html).

**Comment by pastewka** [comment]
> Since we're making documentation changes, I think it would be interesting to setup documentation builds on pull-requests.

I'm not sure how to do this outside of readthedocs. We could have subfolder for each MR, but that can blow up quickly. Maybe there is some hook to remove those when the PR is closed.

**Comment by pastewka** [comment]
I'm merging this to main in preparation for submission to JOSS. Please prepare further documentation changes as PR to main.

**Review by prs513rosewood — APPROVED** [review]

**Pull request merged**
