### PR TITLE
ENH: Cubic Crystal Dislocation Quadrupoles

### PR DESCRIPTION
**Pull request by thomas-rocke**

### CODE REVIEW

**Comment by thomas-rocke** [comment]
Adds new `CubicCrystalDislocationQuadrupole` class (which is also aliased as `Quadrupole` for the end user). 

Features:
- Construction of quadrupole cylinders (similar to `CubicCrystalDissociatedDislocation`, but with full dislocs of opposite Burgers vectors)
- Construction of a periodic quadrupole cell
- Initial guess for a glide barrier in periodic quadrupole cell
- Infinite single-kink of periodic cell

**Comment by thomas-rocke** [comment]
Added refactor of `build_cylinder` and other minor things, to improve maintainability and add additiional use cases:

- `build_cylinder` now a thin wrapper to a more general constructor, to make better use of the similarity of the problems between CCD and CCDD classes. Should also make it easier to expand to systems involving >2 cores (e.g. for dislocation-dislocation interactions)
- Self-consistent displacements for CCDD changed: now an SCF of the dislocation sum, rather than the sum of separate SCFs
- Swapped the `use_atomman` boolean arg from the ADSL commit to a `method=` approach. Should allow easy extension to further solver types.
- Expanded available means of feeding in elastic constants to CCD, CCDD, and `AnisotropicDislocation` - new `C=` arg in the `__init__`, which takes the 6x6 matrix (can also handle the 3x3x3x3 tensor, mainly as a side effect)
- Some bugfixes & unittests

**Comment by thomas-rocke** [comment]
Overhaul of the `test_dislocation.py` framework for testing the `CubicCrystalDislocation` and `CubicCrystalDissociatedDislocation` classes.
- `pytest`-based class solution
- Multiple tests per dislocation type, and use of subtests means maximum coverage, and minimum skipped tests.
- Per-dislocation tests achieved using `pytest.mark.parametrize`
- On-the-fly discovery of dislocations for `parametrize` -> automatic coverage of new dislocation types
-  Full benchmarking of all displacement methods, for all dislocation types, automatically.

**Comment by jameskermode** [comment]
Looking nearly good to go! Can you please add 1-2 bullet points to ChangeLog.md?

**Comment by thomas-rocke** [comment]
Changelog modified, so should be good to go, pending tests passing.

Bit of a temp fix for `view_quad` - the dislocation lines are incorrectly placed (because the cell makes the coordinate system for the ngl objects a bit messy), so I've disabled them for now. Ideally this should be fixed and the lines added back in, but it's not impactful enough to warrant a massive delay on the PR. Will try to figure this out in the coming weeks.

**Comment by thomas-rocke** [comment]
Output of the pytest `parametrize`d tests is not ideal for all `test_*` files. Will look for a quick fix, or revert my change to `conftest.py`

**Pull request merged**
