### PR TITLE
 MAINT: update opls IO for ase > 3.17.0

### PR DESCRIPTION
**Pull request by threich**
get_lammps_prism_str() and positions_to_lammps_strs() are removed from prism class in ASE. @aklemenz  could you please check? Thanks!

### CODE REVIEW

**Comment by aklemenz** [comment]
I updated the master branch, the code should work with all ase versions now.
The proposed changes in io.opls.py might work, but the type conversions were unclean.

**Comment by pastewka** [comment]
Somehow this cannot merge automatically. Can you check what is going on @aklemenz @threich

**Comment by threich** [comment]
@aklemenz pushed his modifications directly to the master branch making this pull request unnecessary. I close the pull request as the master is now already fixed.

@aklemenz  Thanks!

**Comment by pastewka** [comment]
Okay!

**Comment by pastewka** [comment]
Thanks @aklemenz @threich

**Pull request closed without merging**
